# application.yml
spring:
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
      routes:
        - id: service_route
          uri: http://localhost:8081/
          predicates:
            - Path=/service/**
